#cloud-config

---
coreos:
  update:
    reboot-strategy: etcd-lock
  units:
  - name: update-engine.service
    command: stop
  - name: locksmithd.service
    command: stop
  - name: docker.socket
    command: stop
  - name: docker.service
    command: stop
    drop-ins:
      - name: 30-log-opt.conf
        content: |
          [Service]
          Environment="DOCKER_OPTS=--log-opt max-size=100m --log-opt max-file=2"
  - name: bootstrap.service
    command: start
    content: |
      [Unit]
      Description=Bootstrap script to bring the cluster up
      After=network.target

      [Service]
      ExecStart=/opt/bin/bootstrap.sh
      RemainAfterExit=yes
      Type=oneshot

      [Install]
      WantedBy=multi-user.target
  - name: etcd3.service
    command: start
    content: |
      [Unit]
      Description=etcd3
      Documentation=https://github.com/coreos/etcd
      Requires=bootstrap.service
      After=bootstrap.service

      [Service]
      EnvironmentFile=/opt/env/host.env
      ExecStartPre=/bin/mkdir -p /var/lib/etcd3
      ExecStart=/opt/bin/etcd \
        --data-dir=/var/lib/etcd3 \
        --name={{ HOST_NAME }} \
        --initial-advertise-peer-urls=http://$private_ipv4:2380 \
        --listen-peer-urls=http://$private_ipv4:2380 \
        --listen-client-urls=http://$private_ipv4:2379,http://127.0.0.1:2379 \
        --advertise-client-urls=http://$private_ipv4:2379 \
        --initial-cluster-token=etcd-cluster-1 \
        --initial-cluster-state=new \
        --initial-cluster=core-01=http://192.168.58.101:2380,core-02=http://192.168.58.102:2380,core-03=http://192.168.58.103:2380 \
        --snapshot-count=25000 \
        --heartbeat-interval=250 \
        --election-timeout=2500
      Type=notify

      [Install]
      WantedBy=multi-user.target
  - name: kube-flanneld.service
    command: start
    content: |
      [Unit]
      Description=Flannel networking system for Kubernetes
      Documentation=https://github.com/coreos/flannel
      Requires=etcd3.service
      After=etcd3.service

      [Service]
      ExecStartPre=/opt/bin/etcdctl --endpoints=http://192.168.58.101:2379,http://192.168.58.102:2379,http://192.168.58.103:2379 set /coreos.com/network/config '{"Network":"172.17.0.0/16"}'
      ExecStart=/opt/bin/flanneld \
        -ip-masq=true \
        -iface=eth1 \
        -etcd-endpoints=http://192.168.58.101:2379,http://192.168.58.102:2379,http://192.168.58.103:2379
      ExecStartPost=/opt/bin/kube-flanneld-watch.sh
      Restart=always
      RestartSec=10
  - name: kube-kubelet.service
    command: start
    content: |
      [Unit]
      Description=Kubernetes Agent
      Documentation=http://kubernetes.io/docs/admin/kubelet/
      Requires=kube-flanneld.service
      After=kube-flanneld.service

      [Service]
      EnvironmentFile=/opt/env/host.env
      ExecStart=/opt/bin/kubelet \
       --hostname-override={{ HOST_IP }} \
       --register-node=true \
       --allow-privileged=true \
       --cluster_dns=10.3.0.2 \
       --cluster_domain=cluster.local \
       --logtostderr=true \
       --pod-infra-container-image=registry.kkops.cc/google_containers/pause-amd64:3.0 \
       --kubeconfig=/opt/kube/worker-kubeconfig.yaml \
       --tls-cert-file=/opt/ssl/worker.pem \
       --tls-private-key-file=/opt/ssl/worker-key.pem
      Restart=always
      RestartSec=10
  - name: kube-proxy.service
    command: start
    content: |
      [Unit]
      Description=Kubernetes Proxy
      Documentation=http://kubernetes.io/docs/admin/kube-proxy/
      Requires=kube-kubelet.service
      After=kube-kubelet.service

      [Service]
      ExecStart=/opt/bin/kube-proxy \
       --kubeconfig=/opt/kube/worker-kubeconfig.yaml \
       --hostname-override={{ HOST_IP }}
       --proxy-mode=iptables
      Restart=always
      RestartSec=10

write_files:
  - path: "/opt/bin/bootstrap.sh"
    permissions: '0755'
    owner: root
    encoding: gzip+base64
    content: H4sICLEQqVoAA2Jvb3RzdHJhcC5zaADFWGmTm0gS/c6vYD2O6ZnRqgFdiNnxRhSnkAQSl67ZCQeC4hCnAInD6/++oD5st3tm7f2yKEJCma9eZh1ZlVk//A07+jF2NHMPyWGB9mGFID+gkZkXMEMQ30F//x3tOyiWpMUNmUHTrtE//vgHWngwRtD2gZaXoHcazK4wQ83wAeHHfuGbod9A++4BVfkFiiOO3/F7SV7kiGUW6D9RDBYWdhOgv/2GciseIQbkPd5+CPT2hIllhh0AefuT71hJ7PguCguPQP+NuhlMW6fROz+Gxb+Od63ILAP07kOa+XHhoG8HH+9+vrG8/amjiM0I/owQ1OCemEzvx9N7Au+sWPZ9aQYwvrcshMA7+ZS4J4aTVpUk90GQpPkrqgy6fl5k9SdA533bPdO20RyGDpqbKZolSYFaJmrBrPAdv+00bEenSNC8bgc5+nwU8jzEOliOtQ3vUxg9jUi/e2hOEGWU4VRd5EUG6NxNikiiyF9YhgETxgWlSANXnAM5ISb2ZZ02SSIBXGC0s6CJxyGrcDRTGkASgoppwJx25Q1Cg70OAnklqVzJlnt2oygiCzzdFPjLAfc8U+dUCUwFQBgcXZaiMfC8Y2SL+21QsSxYIB0LDVpDhEwbLCdJILmBmbJkDZzgJdUtefdG3OIpXdkAt5OL/HytE4qLKDhXzjxLlnS3lBpQS6xUSiep3nayUys7iaNn2YlOJSUvGeVGKHDlnEX00ycXGfCli5wO1g8eWhLDy8l+O441gW9JypJ58GqBsEDu3Lr15wGcd92RVZ3bS/T+RgzKcm3gvCLyrVyjNR2nDJGT6XYCGEQ8AZl2g7MX+AJV4jRQOB6AFQPcKegAjLto3znQDFe4qRp0op5SUuYdiTYh2ywvCHmNcrgXwpqMmFO2wC/NKGNTSNmXQeWq/GY2bFRvGoYKqMeyt0sJjs+lLPQDLqj3i6uLrJ2Fa2E7+eJdKpJZJWRGb87pGCOoVdlYPfqaxaN8MRg5GSnwvAidY1legHjBxOWObbwMObu5YU0uo26KzKogD+erGU+mEY7PK4GnNSAbHE5WwwXc2rXK5g3AyDhiV/g18XeqMUOEE+We5461DYw9tdhI5nIs9qRpZhsyt9auE3y5VTRd4ScGsCIHaMWRWZTZghQcKEXl6YJkC03pnc67gJMXWGyru3GkyLFN91ifni9HssCWnMOpWAr32xEm9Phl6Yh1jyciVySTkY3UDglNPDaiZX0Jj46zSAz5CgpDKfN5OzkRkUrXba9ans3G7ekGjENgYBqw8rIpj86lQcL1hIXisDmqPVrg7F7ZK6odxZIeMSYGw0jfcsnGEMTAZIZkb8kvlzS7pK6LOKyH+bp31BF2osTFRu9x43BkXiRMWBF0eRRI4mjDZbG3xHLQbIfi6XChCt0gr1PmQGm8Md7r5ojCjDky46KSYkLCTKA+4mdEddhNTnjhR2UE+OsY1By1n29AtAnPcKGoUbbMpKmaSYsBNARDPiCSv1nNieua3zqzS52dLfJiUNtVqBz29rYHiZ24pmYUGCWXgJA3o23GH5YbyzBolXeMctJDTirlcKtweRmU5YjyzqTexRQHgCmfpDbeZl3kqfiKpvccv1ZPztFSR4lXTLB6qp2kDVLm2mIX50CibxFpi6XSBpEJXgM/Yx+i1+ZKjkawUuGltjlwpiXr3qytgTLD2qhigSsIr21pYNTuiQoNUo87IXLFh+O4WJaGKwdxz+Pw01rke+uNx2y9PNB6VU0ph4Q23fXVcJUkUZxmxO2aMjvQmBgSiCaPI1Giro4tkY6QU1scnrlz4jlKeTAUbEPY9nJH2py9xUO+lHRASAbrZ8JGcIa861uIGSb02J56Rz49LWty30vTZW7MN/vcM8O8jU4yO51YSKsHx0ivcHrAgjo3zbOzaDx/fjGQsTJW19fpeLqqB8TquGhj9lzFOhcW2mg7WFajdEYtrqG+SCMmIiQGJ2kCa7Z+PL/OOL0xkGUDJqKrH31yYxTnzRRYvJ0cCs7CmtNomXJTYTcKRarZCqnt09dqsloQ0FDPI2ejzbFtijTcXJzt96lWK+ESL/WrZk+HIHSPJ97U+DW7rXytTvHdPNoHRVgl9Hy3UVZlPs0FsWFxClEmozUxpY/zA7VQNvW65mHd7KM5U6cHgONlwulBGbZDqiqHGb7aKWLCDrGIMMameFkdlsg6xobXs10lJ+tciVndpMtrJnA4vd7uWYehF1wMs954P25nK2R2K/EoTgfxgWqaOOGFgkKy/BCRIeCNgGSk3lxWhXSbDOBMDNPlVCenXKVNRJne9TjpWFUjebWb+sz86PqSUlUTgUbifRsDlnhY0NCsVnYxo6MJRlfbajvZ7Bu+ErBqXWCFGqaTw1D3e0xC+4u1MSLNg1w7QYa4vqhBXshUramIGVsYkwCLvGBre1dtNL/Og/A4aJR37x6OeE5mvz7gH5OKS2p3qcOXmQTyIO1bZv8zad7hVU5bGSrDvdc4dcOpbULSJWjIC/E7ryjS/FcM+zzPaVtbbRrXWrP9DHWSDG1TPzOrkSjoBP30OR/soGmbg5kZfMD4rXHL/qS3LlmI9tUV+ubthxemP2JOaMYxDKH99Ga/QX/8EbW8KLFRs1ehT+K/pgkuR5i1+R/Mb699M/UfOvuC7Uvl93G2aWeRJWEIs35kxqb7OvnXqO+zklsetC/h6+TPyu/iDGHxClkr/T7P0iyp6te8uim+i8sqwleIWulfs7QJsn37etG4E31jy68tP0q7Jdt/Zdm3CfmLNd9JWpydlHGYmHbeFgEhbPOk4ouofIqADv2Xrt0yfrNL9d/8d+Dz0u0HsP7eNt+IL5Ms+C4DDw2+1Rs78uPv8b7DP2K9dshvxdSvt4rql+c566otP84LM7YgGsEia4/fLycNxtenMuvx763gvG9fniqs2UrT38tA4t59XijepOL63f9YeCILg+beg7X40Kf3hrp89+Zpw/2s5nzztMdb6ctKsa0TX5SGiPVpKT6una8gf34qlGZbhnerHrXCS1fko7d6vdN4fgi7cv/tT49Rgfb7MLbTpO1QjnZut14/l86TrnT+dTAkqb9/u6r9Hk9umifzfQ+aYeE9jejdk1d+a/GmqbuhLS20H/6M9mOIErfLBztpPf50+bB9vVf39/d3j7g8hC09Mc5vwRvDh1uOLHjsfpFcLO/FLQfywN2h75D/9wLJL3bSHuHtkvfRNzn24QP67BD68SP29sPz34+Y++ZxQdwuGOzHX+yX+24n8C34Z2Ti+jMqcf0NRP8BmXbTcD8SAAA=
  - path: "/opt/bin/kube-flanneld-watch.sh"
    permissions: '0755'
    owner: root
    encoding: gzip+base64
    content: H4sIAG3J5FkAA1WOQU/DMAyF7/4VoePa5cRtRdpGJ01sbWHdOUqDJyLStMTOBP+eRoCgJ1t+33t+ixvZWS87Ta8AhCxy/JgWhziKOwJYCOuBhhgMChmilxenvUcnKXYeeYn+mqAhMhjN4n4O/Uz1Mpg3DGoYmZJDrFZlvYOHevtYPqu6adVm3xRZnnd2LG53h3VVlQd1Om+qss3+Y/vmuD49JdKOea/pvbhoRzhjju05AT3Hv6jplkF6OVUl1oHFdyNBGK7WINAnMfaG3Uxe/spfCh7P0yYBAAA=
  - path: "/opt/kube/worker-kubeconfig.yaml"
    permissions: '0644'
    owner: root
    encoding: gzip+base64
    content: H4sIAFYQ5lkAA2WPQRKDIAxF95yCCyDTLdveoXsa08qA4EDQevsipY6Ou4T/P+9HCMH0ZB4Ykwle8fnGrPG94vfgX+bNwOVERVRMcK9HVNwF0I5x3hRVxrJgJPMyoAmFzjSEaGhVXIaJZEpOgu4mHKs1YZxLjA9EU1JSQt8t2qLvAFhOJ5TNT3RIJbYJjeQMehIH4AGzhGgx7qjmtbhePNtj9UHwhB+q1Db/Qb/79oNbi0OrU0vR0gxyjLVi++1i+AJZl1LGdAEAAA==
